<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>paprika</artifactId>
	<groupId>de.svenkubiak</groupId>
	<version>0.7.0</version>
	<packaging>jar</packaging>
	<url>https://github.com/svenkubiak/paprika</url>
	<properties>
		<mangooio.version>10.11.5</mangooio.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<jdk.version>25</jdk.version>
		<node.version>v24.20.0</node.version>
	</properties>
	<build>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*</include>
				</includes>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>**/*</include>
				</includes>
				<excludes>
					<exclude>jpackage/**</exclude>
				</excludes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>2.0.2</version>
				<configuration>
					<workingDirectory>admin-ui</workingDirectory>
					<installDirectory>${project.basedir}/.frontend</installDirectory>
				</configuration>
				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>${node.version}</nodeVersion>
							<npmVersion>11.2.0</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
					<execution>
						<id>npm build</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<phase>generate-resources</phase>
						<configuration>
							<arguments>run build</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.5.0</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>${project.basedir}/src/main/resources/files/assets/js</directory>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>${project.basedir}/src/main/resources/files/assets/css</directory>
							<followSymlinks>false</followSymlinks>
						</fileset>
						<fileset>
							<directory>${project.basedir}/src/main/resources/files/assets/admin</directory>
							<followSymlinks>false</followSymlinks>
						</fileset>
					</filesets>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>versions-maven-plugin</artifactId>
				<version>2.21.0</version>
				<configuration>
					<ruleSet>
						<ignoreVersions>
							<ignoreVersion>
								<type>regex</type>
								<version>.*(beta|Beta|alpha|Alpha|rc|RC).*</version>
							</ignoreVersion>
						</ignoreVersions>
					</ruleSet>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>3.2.0</version>
				<executions>
					<execution>
						<id>clean-stale-admin-target-assets</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<delete dir="${project.build.outputDirectory}/files/assets/js" quiet="true" />
								<delete dir="${project.build.outputDirectory}/files/assets/css" quiet="true" />
								<delete dir="${project.build.outputDirectory}/files/assets/admin" quiet="true" />
								<delete file="${project.build.outputDirectory}/files/assets/manifest.json" quiet="true" />
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.16.0</version>
				<configuration>
					<release>25</release>
					<debug>false</debug>
					<showDeprecation>true</showDeprecation>
					<fork>true</fork>
					<compilerArgs>
						<arg>-parameters</arg>
						<arg>-J-Xmx2G</arg>
					</compilerArgs>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>5.8.0.7211</version>
			</plugin>
			<plugin>
				<groupId>io.mangoo</groupId>
				<artifactId>mangooio-maven-plugin</artifactId>
				<version>${mangooio.version}</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<forkedProcessExitTimeoutInSeconds>120</forkedProcessExitTimeoutInSeconds>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<excludes>
						<exclude>**/log4j2-test*</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.2</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<transformers>
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ApacheLicenseResourceTransformer" />
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ApacheNoticeResourceTransformer" />
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer" />
								<transformer
									implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>io.mangoo.core.Application</mainClass>
									<manifestEntries>
										<Multi-Release>true</Multi-Release>
									</manifestEntries>
								</transformer>
							</transformers>
							<artifactSet>
								<excludes>
									<exclude>junit:*</exclude>
									<exclude>rhino:*</exclude>
									<exclude>io.bit3:*</exclude>
									<exclude>com.hazelcast:*</exclude>
									<exclude>org.eclipse.jetty:*</exclude>
									<exclude>org.glassfish.jersey.media:*</exclude>
									<exclude>org.glassfish.jersey.core:*</exclude>
									<exclude>org.glassfish.hk2:*</exclude>
									<exclude>org.glassfish.hk2.external:*</exclude>
									<exclude>com.google.code.findbugs:*</exclude>
									<exclude>com.google.xing:*</exclude>
									<exclude>com.icegreen:*</exclude>
									<exclude>org.hamcrest:*</exclude>
									<exclude>org.cactoos:*</exclude>
									<exclude>org.llorllale:*</exclude>
								</excludes>
							</artifactSet>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<promoteTransitiveDependencies>true</promoteTransitiveDependencies>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.DSA</exclude>
										<exclude>META-INF/*.RSA</exclude>
									</excludes>
								</filter>
							</filters>
							<finalName>paprika</finalName>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.6.3</version>
				<configuration>
					<rules>
						<DependencyConvergence>
							<uniqueVersions>false</uniqueVersions>
						</DependencyConvergence>
					</rules>
				</configuration>
				<executions>
					<execution>
						<id>enforce</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<phase>validate</phase>
					</execution>
					<execution>
						<id>enforce-maven</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireMavenVersion>
									<version>3.9.10</version>
								</requireMavenVersion>
							</rules>
						</configuration>
					</execution>
					<execution>
						<id>enforce-ban-circular-dependencies</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<banCircularDependencies/>
							</rules>
							<fail>true</fail>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>extra-enforcer-rules</artifactId>
						<version>1.12.0</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.6.3</version>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>io.mangoo</groupId>
			<artifactId>mangooio-core</artifactId>
			<version>${mangooio.version}</version>
		</dependency>
		<dependency>
			<groupId>io.mangoo</groupId>
			<artifactId>mangooio-test</artifactId>
			<version>${mangooio.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<profiles>
		<profile>
			<id>package-deb-x86</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>3.6.3</version>
						<executions>
							<execution>
								<id>jpackage-deb-x86</id>
								<phase>package</phase>
								<goals>
									<goal>exec</goal>
								</goals>
								<configuration>
									<executable>jpackage</executable>
									<arguments>
										<argument>--type</argument>
										<argument>deb</argument>
										<argument>--name</argument>
										<argument>paprika</argument>
										<argument>--input</argument>
										<argument>${project.build.directory}</argument>
										<argument>--main-jar</argument>
										<argument>paprika.jar</argument>
										<argument>--main-class</argument>
										<argument>io.mangoo.core.Application</argument>
										<argument>--app-version</argument>
										<argument>${project.version}</argument>
										<argument>--dest</argument>
										<argument>${project.build.directory}/dist</argument>
										<argument>--install-dir</argument>
										<argument>/opt</argument>
										<argument>--linux-package-name</argument>
										<argument>paprika</argument>
										<argument>--resource-dir</argument>
										<argument>${project.basedir}/src/main/resources/jpackage</argument>
									</arguments>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>package-deb-arm64</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>3.6.3</version>
						<executions>
							<execution>
								<id>jpackage-deb-arm64</id>
								<phase>package</phase>
								<goals>
									<goal>exec</goal>
								</goals>
								<configuration>
									<executable>jpackage</executable>
									<arguments>
										<argument>--type</argument>
										<argument>deb</argument>
										<argument>--name</argument>
										<argument>paprika</argument>
										<argument>--input</argument>
										<argument>${project.build.directory}</argument>
										<argument>--main-jar</argument>
										<argument>paprika.jar</argument>
										<argument>--main-class</argument>
										<argument>io.mangoo.core.Application</argument>
										<argument>--app-version</argument>
										<argument>${project.version}</argument>
										<argument>--dest</argument>
										<argument>${project.build.directory}/dist</argument>
										<argument>--install-dir</argument>
										<argument>/opt</argument>
										<argument>--linux-package-name</argument>
										<argument>paprika</argument>
										<argument>--resource-dir</argument>
										<argument>${project.basedir}/src/main/resources/jpackage</argument>
									</arguments>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>ci</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jacoco</groupId>
						<artifactId>jacoco-maven-plugin</artifactId>
						<version>0.8.15</version>
						<executions>
							<execution>
								<id>prepare-agent</id>
								<goals>
									<goal>prepare-agent</goal>
								</goals>
							</execution>
							<execution>
								<id>report</id>
								<goals>
									<goal>report</goal>
								</goals>
								<configuration>
									<formats>
										<format>XML</format>
									</formats>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>